version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ./backend/.env
